[project]
name = "promptgen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dspy>=2.6.10",
    "flask>=3.1.0",
    "hyperon>=0.2.2",
    "tabulate>=0.9.0",
]
